BASE_URL="https://www.coingecko.com/en/coins/"
MATCHING_RE=r"\<meta name\=\"description\" content\=\".+\""
PRICE_RE=r"Bitcoin is USD \$[0-9,]*\.[0-9]*"
VOLUME_RE=r"volume of \$[0-9,]*"
CHANGE_RE=r"[\-0-9\.,]*\% in the last 24 hours"
